name: Build and Push Docker Images on Merge

concurrency:
  group: main-release
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU and Docker Buildx
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Expose GH Runtime
        uses: crazy-max/ghaction-github-runtime@v3

      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: "${{ github.repository_owner }}"

      - name: set lower case owner name
        run: |
          echo "REPO_LC=$(echo ${{ github.repository }} | awk 'BEGIN{FS=OFS="/"}{print tolower($1) "/" $2}')" >>${GITHUB_ENV}
      - name: Build and Push Docker Images
        run: |
          make build_and_push_images
        env:
          REGISTRY: "ghcr.io"
          ORG: ${{ env.OWNER_LC }}
          REPO: ${{ env.REPO_LC }}
          GITHUB_WORKFLOW: ${{ github.workflow }}

  build-tauri:
    runs-on: [macos-latest]
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin,x86_64-apple-darwin

      - name: Rust Cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./tauri/src-tauri"

      - name: Set up Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install frontend dependencies
        run: cd tauri && npm install

      - name: Tauri build
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: "./tauri"
          args: "--target universal-apple-darwin"
